import type { CharacterMoveset } from './types';

export const RYU_MOVESET: CharacterMoveset = {
  id: 'ryu',
  displayName: 'Ryu',
  archetype: 'shoto',
  personality: {
    aggression: 0.50,
    patience: 0.60,
    execution: 0.80,
    riskTolerance: 0.45,
  },
  roles: {
    fireball_fast:    ['hadouken_jab', 'hadouken_strong'],
    fireball_strong:  ['hadouken_fierce', 'hadouken_strong'],
    anti_air:         ['shoryu_fierce', 'shoryu_strong'],
    anti_air_safe:    ['shoryu_jab'],
    anti_air_normal:  ['crouch_fierce', 'standing_fierce'],
    approach:         ['tatsu_hk', 'tatsu_mk', 'walk_forward'],
    air_approach:     ['air_tatsu_hk', 'air_tatsu_mk'],
    jump_in_safe:     ['jump_forward_mk', 'jump_forward_mp'],
    jump_in_reward:   ['jump_forward_hk', 'jump_forward_hp'],
    footsie_poke:     ['crouch_mk', 'standing_forward'],
    long_poke:        ['standing_rh'],
    sweep:            ['sweep'],
    big_punish:       ['shoryu_fierce'],
    block:            ['block_crouch'],
    block_high:       ['block_stand'],
    walk_back:        ['walk_back'],
    walk_forward:     ['walk_forward'],
    jump_back_escape: ['jump_back_hk', 'jump_back'],
    reset_space:      ['walk_back', 'jump_back'],
    throw_tech:       ['throw_forward'],
    throw_back:       ['throw_back'],
    whiff_special:    ['whiff_shoryu_midscreen', 'whiff_throw'],
    walk_into_projectile: ['walk_into_fireball'],
    unsafe_jump:      ['empty_jump', 'jump_forward_lk'],
  },
};
