/**
 * CPS1 Game Catalog — extracted from MAME 0.286
 * Source: mamedev/mame src/mame/capcom/cps1.cpp
 * https://github.com/mamedev/mame/blob/master/src/mame/capcom/cps1.cpp
 * 39 parent games, 193 clones, 232 total
 */

export interface CPS1GameEntry {
  /** MAME ROM set name */
  name: string;
  /** Human-readable description */
  description: string;
  /** Parent ROM set name (empty string for parent sets) */
  parent: string;
}

export const CPS1_GAME_CATALOG: CPS1GameEntry[] = [
  { name: '1941', description: '1941: Counter Attack (World 900227)', parent: '' },
  { name: '1941j', description: '1941: Counter Attack (Japan)', parent: '1941' },
  { name: '1941r1', description: '1941: Counter Attack (World)', parent: '1941' },
  { name: '1941u', description: '1941: Counter Attack (USA 900227)', parent: '1941' },
  { name: '3wonders', description: 'Three Wonders (World 910520)', parent: '' },
  { name: '3wondersb', description: 'Three Wonders (bootleg)', parent: '3wonders' },
  { name: '3wondersbi', description: 'Three Wonders (Italian bootleg)', parent: '3wonders' },
  { name: '3wondersh', description: 'Three Wonders (hack)', parent: '3wonders' },
  { name: '3wondersr1', description: 'Three Wonders (World 910513)', parent: '3wonders' },
  { name: '3wondersu', description: 'Three Wonders (USA 910520)', parent: '3wonders' },
  { name: 'area88', description: 'Area 88 (Japan)', parent: 'unsquad' },
  { name: 'area88r', description: 'Area 88 (Japan Resale Ver.)', parent: 'unsquad' },
  { name: 'captcomm', description: 'Captain Commando (World 911202)', parent: '' },
  { name: 'captcommb', description: 'Captain Commando (bootleg)', parent: 'captcomm' },
  { name: 'captcommj', description: 'Captain Commando (Japan 911202)', parent: 'captcomm' },
  { name: 'captcommjr1', description: 'Captain Commando (Japan 910928)', parent: 'captcomm' },
  { name: 'captcommr1', description: 'Captain Commando (World 911014)', parent: 'captcomm' },
  { name: 'captcommu', description: 'Captain Commando (USA 910928)', parent: 'captcomm' },
  { name: 'cawing', description: 'Carrier Air Wing (World 901012)', parent: '' },
  { name: 'cawingj', description: 'U.S. Navy (Japan 901012)', parent: 'cawing' },
  { name: 'cawingjr', description: 'U.S. Navy (Japan Resale Ver. 901130)', parent: 'cawing' },
  { name: 'cawingr1', description: 'Carrier Air Wing (World 901009)', parent: 'cawing' },
  { name: 'cawingu', description: 'Carrier Air Wing (USA 901130)', parent: 'cawing' },
  { name: 'cawingur1', description: 'Carrier Air Wing (USA 901012)', parent: 'cawing' },
  { name: 'chikij', description: 'Chiki Chiki Boys (Japan 900619)', parent: 'mtwins' },
  { name: 'cworld2j', description: 'Adventure Quiz Capcom World 2 (Japan 920611)', parent: '' },
  { name: 'cworld2ja', description: 'Adventure Quiz Capcom World 2 (Japan 920611, B-Board 90629B-3, no battery)', parent: 'cworld2j' },
  { name: 'cworld2jb', description: 'Adventure Quiz Capcom World 2 (Japan 920611, B-Board 91634B-2)', parent: 'cworld2j' },
  { name: 'daimakai', description: 'Daimakaimura (Japan)', parent: 'ghouls' },
  { name: 'daimakair', description: 'Daimakaimura (Japan Resale Ver.)', parent: 'ghouls' },
  { name: 'dino', description: 'Cadillacs and Dinosaurs (World 930201)', parent: '' },
  { name: 'dinoa', description: 'Cadillacs and Dinosaurs (Asia TW 930223)', parent: 'dino' },
  { name: 'dinohunt', description: 'Dinosaur Hunter (Chinese bootleg of Cadillacs and Dinosaurs)', parent: 'dino' },
  { name: 'dinoj', description: 'Cadillacs: Kyouryuu Shin Seiki (Japan 930201)', parent: 'dino' },
  { name: 'dinou', description: 'Cadillacs and Dinosaurs (USA 930201)', parent: 'dino' },
  { name: 'dynwar', description: 'Dynasty Wars (USA, B-Board 89624B-?)', parent: '' },
  { name: 'dynwara', description: 'Dynasty Wars (USA, B-Board 88622B-3)', parent: 'dynwar' },
  { name: 'dynwarj', description: 'Tenchi wo Kurau (Japan)', parent: 'dynwar' },
  { name: 'dynwarjr', description: 'Tenchi wo Kurau (Japan Resale Ver.)', parent: 'dynwar' },
  { name: 'ffight', description: 'Final Fight (World, set 1)', parent: '' },
  { name: 'ffighta', description: 'Final Fight (World, set 2)', parent: 'ffight' },
  { name: 'ffightae', description: 'Final Fight 30th Anniversary Edition (World, hack)', parent: 'ffight' },
  { name: 'ffightj', description: 'Final Fight (Japan)', parent: 'ffight' },
  { name: 'ffightj1', description: 'Final Fight (Japan 900112)', parent: 'ffight' },
  { name: 'ffightj2', description: 'Final Fight (Japan 900305)', parent: 'ffight' },
  { name: 'ffightj3', description: 'Final Fight (Japan 900405)', parent: 'ffight' },
  { name: 'ffightj4', description: 'Final Fight (Japan 900613)', parent: 'ffight' },
  { name: 'ffightjh', description: 'Street Smart / Final Fight (Japan, hack)', parent: 'ffight' },
  { name: 'ffightu', description: 'Final Fight (USA, set 1)', parent: 'ffight' },
  { name: 'ffightu1', description: 'Final Fight (USA, set 2)', parent: 'ffight' },
  { name: 'ffightua', description: 'Final Fight (USA 900112)', parent: 'ffight' },
  { name: 'ffightub', description: 'Final Fight (USA 900424)', parent: 'ffight' },
  { name: 'ffightuc', description: 'Final Fight (USA 900613)', parent: 'ffight' },
  { name: 'forgottn', description: 'Forgotten Worlds (World, newer)', parent: '' },
  { name: 'forgottna', description: 'Forgotten Worlds (World)', parent: 'forgottn' },
  { name: 'forgottnj', description: 'Forgotten Worlds (Japan) (English prototype)', parent: 'forgottn' },
  { name: 'forgottnu', description: 'Forgotten Worlds (USA, B-Board 88621B-2, Rev. C)', parent: 'forgottn' },
  { name: 'forgottnua', description: 'Forgotten Worlds (USA, B-Board 88618B-2, Rev. A)', parent: 'forgottn' },
  { name: 'forgottnuaa', description: 'Forgotten Worlds (USA, B-Board 88618B-2, Rev. AA)', parent: 'forgottn' },
  { name: 'forgottnuc', description: 'Forgotten Worlds (USA, B-Board 88618B-2, Rev. C)', parent: 'forgottn' },
  { name: 'forgottnue', description: 'Forgotten Worlds (USA, B-Board 88618B-2, Rev. E)', parent: 'forgottn' },
  { name: 'ganbare', description: 'Ganbare! Marine Kun (Japan 2K0411)', parent: '' },
  { name: 'ghouls', description: 'Ghouls\'n Ghosts (World)', parent: '' },
  { name: 'ghoulsu', description: 'Ghouls\'n Ghosts (USA)', parent: 'ghouls' },
  { name: 'gulunpa', description: 'Gulun.Pa! (Japan 931220 L) (prototype)', parent: '' },
  { name: 'knights', description: 'Knights of the Round (World 911127)', parent: '' },
  { name: 'knightsb2', description: 'Knights of the Round (bootleg, World 911127)', parent: 'knights' },
  { name: 'knightsj', description: 'Knights of the Round (Japan 911127, B-Board 91634B-2)', parent: 'knights' },
  { name: 'knightsja', description: 'Knights of the Round (Japan 911127, B-Board 89625B-1)', parent: 'knights' },
  { name: 'knightsu', description: 'Knights of the Round (USA 911127)', parent: 'knights' },
  { name: 'kod', description: 'The King of Dragons (World 910805)', parent: '' },
  { name: 'kodj', description: 'The King of Dragons (Japan 910805, B-Board 90629B-3)', parent: 'kod' },
  { name: 'kodja', description: 'The King of Dragons (Japan 910805, B-Board 89625B-1)', parent: 'kod' },
  { name: 'kodr1', description: 'The King of Dragons (World 910711)', parent: 'kod' },
  { name: 'kodr2', description: 'The King of Dragons (World 910731)', parent: 'kod' },
  { name: 'kodu', description: 'The King of Dragons (USA 910910)', parent: 'kod' },
  { name: 'lostwrld', description: 'Lost Worlds (Japan)', parent: 'forgottn' },
  { name: 'lostwrldo', description: 'Lost Worlds (Japan Old Ver.)', parent: 'forgottn' },
  { name: 'mbomberj', description: 'Muscle Bomber: The Body Explosion (Japan 930713)', parent: 'slammast' },
  { name: 'mbombrd', description: 'Muscle Bomber Duo: Ultimate Team Battle (World 931206)', parent: '' },
  { name: 'mbombrdj', description: 'Muscle Bomber Duo: Heat Up Warriors (Japan 931206)', parent: 'mbombrd' },
  { name: 'megaman', description: 'Mega Man: The Power Battle (CPS1, USA 951006)', parent: '' },
  { name: 'megamana', description: 'Mega Man: The Power Battle (CPS1, Asia 951006)', parent: 'megaman' },
  { name: 'mercs', description: 'Mercs (World 900302)', parent: '' },
  { name: 'mercsj', description: 'Senjou no Ookami II (Japan 900302)', parent: 'mercs' },
  { name: 'mercsu', description: 'Mercs (USA 900608)', parent: 'mercs' },
  { name: 'mercsur1', description: 'Mercs (USA 900302)', parent: 'mercs' },
  { name: 'mpumpkin', description: 'Magical Pumpkin: Puroland de Daibouken (Japan 960712)', parent: '' },
  { name: 'msword', description: 'Magic Sword: Heroic Fantasy (World 900725)', parent: '' },
  { name: 'mswordj', description: 'Magic Sword: Heroic Fantasy (Japan 900623)', parent: 'msword' },
  { name: 'mswordr1', description: 'Magic Sword: Heroic Fantasy (World 900623)', parent: 'msword' },
  { name: 'mswordu', description: 'Magic Sword: Heroic Fantasy (USA 900725)', parent: 'msword' },
  { name: 'mtwins', description: 'Mega Twins (World 900619)', parent: '' },
  { name: 'nemo', description: 'Nemo (World 901130)', parent: '' },
  { name: 'nemoj', description: 'Nemo (Japan 901120, 88622B-3 ROM board)', parent: 'nemo' },
  { name: 'nemoja', description: 'Nemo (Japan 901120, 89625B-1 ROM board)', parent: 'nemo' },
  { name: 'nemor1', description: 'Nemo (World 901109)', parent: 'nemo' },
  { name: 'pang3', description: 'Pang! 3 (Europe 950601)', parent: '' },
  { name: 'pang3b', description: 'Pang! 3 (bootleg, set 1)', parent: 'pang3' },
  { name: 'pang3b2', description: 'Pang! 3 (bootleg, set 2)', parent: 'pang3' },
  { name: 'pang3b3', description: 'Pang! 3 (bootleg, set 3)', parent: 'pang3' },
  { name: 'pang3b4', description: 'Pang! 3 (bootleg, set 4)', parent: 'pang3' },
  { name: 'pang3b5', description: 'Pang! 3 (bootleg, set 5)', parent: 'pang3' },
  { name: 'pang3j', description: 'Pang! 3: Kaitou Tachi no Karei na Gogo (Japan 950511)', parent: 'pang3' },
  { name: 'pang3r1', description: 'Pang! 3 (Europe 950511)', parent: 'pang3' },
  { name: 'pmonster', description: 'Gamushara Battle! Puchi Monster (Japan 990519)', parent: '' },
  { name: 'pnickj', description: 'Pnickies (Japan 940608)', parent: '' },
  { name: 'pokonyan', description: 'Pokonyan! Balloon (Japan 940322)', parent: '' },
  { name: 'punisher', description: 'The Punisher (World 930422)', parent: '' },
  { name: 'punisherbz', description: 'Biaofeng Zhanjing (Chinese bootleg of The Punisher)', parent: 'punisher' },
  { name: 'punisherh', description: 'The Punisher (Hispanic 930422)', parent: 'punisher' },
  { name: 'punisherj', description: 'The Punisher (Japan 930422)', parent: 'punisher' },
  { name: 'punisheru', description: 'The Punisher (USA 930422)', parent: 'punisher' },
  { name: 'qad', description: 'Quiz & Dragons: Capcom Quiz Game (USA 920701)', parent: '' },
  { name: 'qadjr', description: 'Quiz & Dragons: Capcom Quiz Game (Japan Resale Ver. 940921)', parent: 'qad' },
  { name: 'qtono2j', description: 'Quiz Tonosama no Yabou 2: Zenkoku-ban (Japan 950123)', parent: '' },
  { name: 'rockmanj', description: 'Rockman: The Power Battle (CPS1, Japan 950922)', parent: 'megaman' },
  { name: 'sf2', description: 'Street Fighter II: The World Warrior (World 910522)', parent: '' },
  { name: 'sf2acc', description: 'Street Fighter II\': Champion Edition (Accelerator!, bootleg, set 1)', parent: 'sf2ce' },
  { name: 'sf2acca', description: 'Street Fighter II\': Champion Edition (Accelerator!, bootleg, set 2)', parent: 'sf2ce' },
  { name: 'sf2accp2', description: 'Street Fighter II\': Champion Edition (Accelerator Pt.II, bootleg)', parent: 'sf2ce' },
  { name: 'sf2amf', description: 'Street Fighter II\': Champion Edition (Alpha Magic-F, bootleg)', parent: 'sf2ce' },
  { name: 'sf2amf2', description: 'Street Fighter II\': Champion Edition (L735 Test Rom, bootleg, set 1)', parent: 'sf2ce' },
  { name: 'sf2amf3', description: 'Street Fighter II\': Champion Edition (L735 Test Rom, bootleg, set 2)', parent: 'sf2ce' },
  { name: 'sf2bhh', description: 'Street Fighter II\': Champion Edition (Hung Hsi, bootleg)', parent: 'sf2ce' },
  { name: 'sf2ce', description: 'Street Fighter II\': Champion Edition (World 920513)', parent: '' },
  { name: 'sf2ceblp', description: 'Street Fighter II\': Champion Edition (protected bootleg on non-dash board)', parent: 'sf2ce' },
  { name: 'sf2cebltw', description: 'Street Fighter II\': Champion Edition (\'Taiwan\' bootleg with PAL)', parent: 'sf2ce' },
  { name: 'sf2ceds6', description: 'Street Fighter II\': Champion Edition (Dstreet-6, bootleg)', parent: 'sf2ce' },
  { name: 'sf2ceea', description: 'Street Fighter II\': Champion Edition (World 920313)', parent: 'sf2ce' },
  { name: 'sf2ceec', description: 'Street Fighter II\': Champion Edition (World 920803)', parent: 'sf2ce' },
  { name: 'sf2ceja', description: 'Street Fighter II\': Champion Edition (Japan 920322)', parent: 'sf2ce' },
  { name: 'sf2cejb', description: 'Street Fighter II\': Champion Edition (Japan 920513)', parent: 'sf2ce' },
  { name: 'sf2cejc', description: 'Street Fighter II\': Champion Edition (Japan 920803)', parent: 'sf2ce' },
  { name: 'sf2cems6a', description: 'Street Fighter II\': Champion Edition (Mstreet-6, bootleg, set 1)', parent: 'sf2ce' },
  { name: 'sf2cems6b', description: 'Street Fighter II\': Champion Edition (Mstreet-6, bootleg, set 2)', parent: 'sf2ce' },
  { name: 'sf2cems6c', description: 'Street Fighter II\': Champion Edition (Mstreet-6, bootleg, set 3)', parent: 'sf2ce' },
  { name: 'sf2cet', description: 'Street Fighter II\': Champion Edition (Taiwan 920313)', parent: 'sf2ce' },
  { name: 'sf2ceua', description: 'Street Fighter II\': Champion Edition (USA 920313)', parent: 'sf2ce' },
  { name: 'sf2ceub', description: 'Street Fighter II\': Champion Edition (USA 920513)', parent: 'sf2ce' },
  { name: 'sf2ceuc', description: 'Street Fighter II\': Champion Edition (USA 920803)', parent: 'sf2ce' },
  { name: 'sf2ceupl', description: 'Street Fighter II\': Champion Edition (Japan 920322, UPL bootleg?)', parent: 'sf2ce' },
  { name: 'sf2dkot2', description: 'Street Fighter II\': Champion Edition (Double K.O. Turbo II, bootleg)', parent: 'sf2ce' },
  { name: 'sf2dongb', description: 'Street Fighter II\': Champion Edition (Dongfang Bubai protection, bootleg)', parent: 'sf2ce' },
  { name: 'sf2ea', description: 'Street Fighter II: The World Warrior (World 910204)', parent: 'sf2' },
  { name: 'sf2eb', description: 'Street Fighter II: The World Warrior (World 910214)', parent: 'sf2' },
  { name: 'sf2ebbl', description: 'Street Fighter II: The World Warrior (TAB Austria, bootleg, set 1)', parent: 'sf2' },
  { name: 'sf2ebbl2', description: 'Street Fighter II: The World Warrior (TAB Austria, bootleg, set 3)', parent: 'sf2' },
  { name: 'sf2ebbl3', description: 'Street Fighter II: The World Warrior (TAB Austria, bootleg, set 4)', parent: 'sf2' },
  { name: 'sf2ed', description: 'Street Fighter II: The World Warrior (World 910318)', parent: 'sf2' },
  { name: 'sf2ee', description: 'Street Fighter II: The World Warrior (World 910228)', parent: 'sf2' },
  { name: 'sf2ef', description: 'Street Fighter II: The World Warrior (World 910411)', parent: 'sf2' },
  { name: 'sf2em', description: 'Street Fighter II: The World Warrior (World 910129)', parent: 'sf2' },
  { name: 'sf2en', description: 'Street Fighter II: The World Warrior (World 910204, conversion)', parent: 'sf2' },
  { name: 'sf2hf', description: 'Street Fighter II\': Hyper Fighting (World 921209)', parent: '' },
  { name: 'sf2hfj', description: 'Street Fighter II\' Turbo: Hyper Fighting (Japan 921209)', parent: 'sf2hf' },
  { name: 'sf2hfu', description: 'Street Fighter II\': Hyper Fighting (USA 921209)', parent: 'sf2hf' },
  { name: 'sf2j', description: 'Street Fighter II: The World Warrior (Japan 911210, CPS-B-13)', parent: 'sf2' },
  { name: 'sf2j17', description: 'Street Fighter II: The World Warrior (Japan 911210, CPS-B-17)', parent: 'sf2' },
  { name: 'sf2ja', description: 'Street Fighter II: The World Warrior (Japan 910214)', parent: 'sf2' },
  { name: 'sf2jc', description: 'Street Fighter II: The World Warrior (Japan 910306)', parent: 'sf2' },
  { name: 'sf2jf', description: 'Street Fighter II: The World Warrior (Japan 910411)', parent: 'sf2' },
  { name: 'sf2jh', description: 'Street Fighter II: The World Warrior (Japan 910522)', parent: 'sf2' },
  { name: 'sf2jl', description: 'Street Fighter II: The World Warrior (Japan 920312)', parent: 'sf2' },
  { name: 'sf2koryu', description: 'Street Fighter II\': Champion Edition (Xiang Long, Chinese bootleg)', parent: 'sf2ce' },
  { name: 'sf2level', description: 'Street Fighter II\': Champion Edition (bootleg with level selection)', parent: 'sf2ce' },
  { name: 'sf2m10', description: 'Street Fighter II\': Champion Edition (M10, bootleg)', parent: 'sf2ce' },
  { name: 'sf2m2', description: 'Street Fighter II\': Champion Edition (M2, bootleg)', parent: 'sf2ce' },
  { name: 'sf2m3', description: 'Street Fighter II\': Champion Edition (M3, bootleg)', parent: 'sf2ce' },
  { name: 'sf2m4', description: 'Street Fighter II\': Champion Edition (M4, bootleg)', parent: 'sf2ce' },
  { name: 'sf2m5', description: 'Street Fighter II\': Champion Edition (M5, bootleg)', parent: 'sf2ce' },
  { name: 'sf2m6', description: 'Street Fighter II\': Champion Edition (M6, bootleg)', parent: 'sf2ce' },
  { name: 'sf2m7', description: 'Street Fighter II\': Champion Edition (M7, bootleg)', parent: 'sf2ce' },
  { name: 'sf2m8', description: 'Street Fighter II\': Champion Edition (M8, bootleg)', parent: 'sf2ce' },
  { name: 'sf2mkot', description: 'Street Fighter II\': Magic KO Turbo!! - Nightmare Crack', parent: 'sf2ce' },
  { name: 'sf2qp1', description: 'Street Fighter II: The World Warrior (Quicken Pt-I, bootleg)', parent: 'sf2' },
  { name: 'sf2qp2', description: 'Street Fighter II: The World Warrior (Quicken, bootleg)', parent: 'sf2' },
  { name: 'sf2rb', description: 'Street Fighter II\': Champion Edition (Rainbow, bootleg, set 1)', parent: 'sf2ce' },
  { name: 'sf2rb2', description: 'Street Fighter II\': Champion Edition (Rainbow, bootleg, set 2)', parent: 'sf2ce' },
  { name: 'sf2rb3', description: 'Street Fighter II\': Champion Edition (Rainbow, bootleg, set 3)', parent: 'sf2ce' },
  { name: 'sf2re', description: 'Street Fighter II\': Champion Edition (RE, bootleg)', parent: 'sf2ce' },
  { name: 'sf2red', description: 'Street Fighter II\': Champion Edition (Red Wave, bootleg, set 1)', parent: 'sf2ce' },
  { name: 'sf2reda', description: 'Street Fighter II\': Champion Edition (Red Wave, bootleg, set 2)', parent: 'sf2ce' },
  { name: 'sf2redp2', description: 'Street Fighter II\': Champion Edition (Red Wave PtII, bootleg)', parent: 'sf2ce' },
  { name: 'sf2rk', description: 'Street Fighter II: The World Warrior (RK, bootleg)', parent: 'sf2' },
  { name: 'sf2rules', description: 'Street Fighter II: The World Warrior (bootleg with rules screen)', parent: 'sf2' },
  { name: 'sf2stt', description: 'Street Fighter II: The World Warrior (TAB Austria, bootleg, set 2)', parent: 'sf2' },
  { name: 'sf2thndr', description: 'Street Fighter II: The World Warrior (Thunder Edition, bootleg, set 1)', parent: 'sf2' },
  { name: 'sf2thndr2', description: 'Street Fighter II: The World Warrior (Thunder Edition, bootleg, set 2)', parent: 'sf2' },
  { name: 'sf2ua', description: 'Street Fighter II: The World Warrior (USA 910206)', parent: 'sf2' },
  { name: 'sf2ub', description: 'Street Fighter II: The World Warrior (USA 910214)', parent: 'sf2' },
  { name: 'sf2uc', description: 'Street Fighter II: The World Warrior (USA 910306)', parent: 'sf2' },
  { name: 'sf2ud', description: 'Street Fighter II: The World Warrior (USA 910318)', parent: 'sf2' },
  { name: 'sf2ue', description: 'Street Fighter II: The World Warrior (USA 910228)', parent: 'sf2' },
  { name: 'sf2uf', description: 'Street Fighter II: The World Warrior (USA 910411)', parent: 'sf2' },
  { name: 'sf2ug', description: 'Street Fighter II: The World Warrior (USA 910522, Rev. G)', parent: 'sf2' },
  { name: 'sf2uh', description: 'Street Fighter II: The World Warrior (USA 910522, Rev. H)', parent: 'sf2' },
  { name: 'sf2ui', description: 'Street Fighter II: The World Warrior (USA 910522, Rev. I)', parent: 'sf2' },
  { name: 'sf2uk', description: 'Street Fighter II: The World Warrior (USA 911101)', parent: 'sf2' },
  { name: 'sf2um', description: 'Street Fighter II: The World Warrior (USA 920312)', parent: 'sf2' },
  { name: 'sf2v004', description: 'Street Fighter II\': Champion Edition (V004, bootleg)', parent: 'sf2ce' },
  { name: 'sf2yyc', description: 'Street Fighter II\': Champion Edition (YYC, bootleg)', parent: 'sf2ce' },
  { name: 'sfach', description: 'Street Fighter Alpha: Warriors\' Dreams (CPS Changer, Publicity USA 950727)', parent: 'sfzch' },
  { name: 'sfzbch', description: 'Street Fighter Zero (CPS Changer, Brazil 950727)', parent: 'sfzch' },
  { name: 'sfzch', description: 'Street Fighter Zero (CPS Changer, Japan 951020)', parent: '' },
  { name: 'slammast', description: 'Saturday Night Slam Masters (World 930713)', parent: '' },
  { name: 'slammastu', description: 'Saturday Night Slam Masters (USA 930713)', parent: 'slammast' },
  { name: 'strider', description: 'Strider (USA, B-Board 89624B-2)', parent: '' },
  { name: 'striderj', description: 'Strider Hiryu (Japan)', parent: 'strider' },
  { name: 'striderjr', description: 'Strider Hiryu (Japan Resale Ver.)', parent: 'strider' },
  { name: 'striderua', description: 'Strider (USA, B-Board 89624B-3)', parent: 'strider' },
  { name: 'strideruc', description: 'Strider (USA, B-Board 90629B-3, buggy Street Fighter II conversion)', parent: 'strider' },
  { name: 'unsquad', description: 'U.N. Squadron (USA)', parent: '' },
  { name: 'varth', description: 'Varth: Operation Thunderstorm (World 920714)', parent: '' },
  { name: 'varthb2', description: 'Varth: Operation Thunderstorm (bootleg, set 2)', parent: 'varth' },
  { name: 'varthb3', description: 'Varth: Operation Thunderstorm (bootleg, set 3)', parent: 'varth' },
  { name: 'varthj', description: 'Varth: Operation Thunderstorm (Japan 920714)', parent: 'varth' },
  { name: 'varthjr', description: 'Varth: Operation Thunderstorm (Japan Resale Ver. 920714)', parent: 'varth' },
  { name: 'varthr1', description: 'Varth: Operation Thunderstorm (World 920612)', parent: 'varth' },
  { name: 'varthu', description: 'Varth: Operation Thunderstorm (USA 920612)', parent: 'varth' },
  { name: 'willow', description: 'Willow (World)', parent: '' },
  { name: 'willowj', description: 'Willow (Japan)', parent: 'willow' },
  { name: 'willowu', description: 'Willow (USA)', parent: 'willow' },
  { name: 'willowuo', description: 'Willow (USA Old Ver.)', parent: 'willow' },
  { name: 'wof', description: 'Warriors of Fate (World 921031)', parent: '' },
  { name: 'wofa', description: 'Sangokushi II (Asia 921005)', parent: 'wof' },
  { name: 'wofch', description: 'Tenchi wo Kurau II: Sekiheki no Tatakai (CPS Changer, Japan 921031)', parent: '' },
  { name: 'wofhfh', description: 'Huo Feng Huang (Chinese bootleg of Sangokushi II)', parent: 'wof' },
  { name: 'wofj', description: 'Tenchi wo Kurau II: Sekiheki no Tatakai (Japan 921031)', parent: 'wof' },
  { name: 'wofr1', description: 'Warriors of Fate (World 921002)', parent: 'wof' },
  { name: 'wofu', description: 'Warriors of Fate (USA 921031)', parent: 'wof' },
  { name: 'wonder3', description: 'Wonder 3 (Japan 910520)', parent: '3wonders' },
];

/** Parent (non-clone) games only */
export const CPS1_PARENT_GAMES = CPS1_GAME_CATALOG.filter(g => !g.parent);

/** Games that use ROT270 (vertical screen) — from MAME */
export const ROT270_GAMES = new Set(['1941', '1941j', '1941r1', '1941u', 'mercs', 'mercsj', 'mercsu', 'mercsur1', 'varth', 'varthb2', 'varthb3', 'varthj', 'varthjr', 'varthr1', 'varthu']);
